### ISSUE TITLE
"Recently played" tab in Fullscreen Mode doesn't update after launching game

### ISSUE THREAD

**Issue by ShadowOfGannicus** [JosefNemec/Playnite#1995]
"Recently played" tab in Fullscreen Mode doesn't update right after launching or closing game, only after switching to other tab and back, switching to desktop mode and back, or restarting Playnite.

**Comment by JosefNemec** [comment]
Done in devel9.

**Comment by JosefNemec** [comment]
Reopen, the fix caused issues in other places. This is a bug in WPF and will require #2499

**Comment by JosefNemec** [comment]
Happens in Desktop mode as well.

**Comment by oryxcallotis** [comment]
Still the same in 2026. The taskbar keeps last played in order properly, but the main window doesn't for me, unless I also group by last played. It's only with 'grouped by' enabled that the main window list of games updates properly.

Taskbar, correct order;

<img width="522" height="869" alt="Image" src="https://github.com/user-attachments/assets/f3320378-1a40-45bb-92b2-c5a2da596a84" />

Main desktop window, incorrect order;

<img width="1080" height="1881" alt="Image" src="https://github.com/user-attachments/assets/8e8f8e63-4f2e-4cd8-ac12-cf1e85138c65" />

Main desktop window, correct order (grouped);

<img width="1088" height="1888" alt="Image" src="https://github.com/user-attachments/assets/97a5216a-bf87-40d7-bad9-e13c887c5078" />

**Comment by oryxcallotis** [comment]
Coming back to this, I'm not even sure that enabling 'grouped by' was what fixed it. It just happened to refresh the game listing when enabling it.

One possible fix for this I have is; insert this script into your global scripts from the main menu settings. I feel like putting it in after a game launches might be best. Some games (like Retroarch) seem to stop it from running, so you could insert it into those problem games, after they get closed (edit the game - scripts). From some testing, the sorting seems to work fine now.

```
Start-Sleep -Milliseconds 2000 

$PlayniteApi.MainView.UIDispatcher.Invoke([action]{
    $dir = $PlayniteApi.MainView.SortOrderDirection
    if ($dir -eq [Playnite.SDK.Models.SortOrderDirection]::Ascending) {
        $PlayniteApi.MainView.SortOrderDirection = [Playnite.SDK.Models.SortOrderDirection]::Descending
        $PlayniteApi.MainView.SortOrderDirection = [Playnite.SDK.Models.SortOrderDirection]::Ascending
    } else {
        $PlayniteApi.MainView.SortOrderDirection = [Playnite.SDK.Models.SortOrderDirection]::Ascending
        $PlayniteApi.MainView.SortOrderDirection = [Playnite.SDK.Models.SortOrderDirection]::Descending
    }
})

[System.Media.SystemSounds]::Beep.Play()
```

<img width="1283" height="954" alt="Image" src="https://github.com/user-attachments/assets/b331fcc5-d3c8-48fb-95d4-e15ae47c6901" />
