### ISSUE TITLE
Playnite 8 Playstation library support fails to authenticate

### ISSUE THREAD

**Issue by adrianluff** [JosefNemec/Playnite#2032]
Playnite 8 fails to import Playstation library games with the error "Object reference not set to an instance of an object." immediately after authenticating from Settings -> Libraries -> PlayStation or "User is not authenticated" after the first attempt.

This issue may be related to two factor authentication being enabled on the PSN account.

Playnite log reports:
> 03-10 23:56:47.535|ERROR|PSNLibrary:Failed to import PSN games.System.NullReferenceException: Object reference not set to an instance of an object.
   at PSNLibrary.PSNLibrary.ParseDownloadList(PSNAccountClient clientApi) in E:\Devel\Playnite\source\Plugins\PSNLibrary\PSNLibrary.cs:line 130
   at PSNLibrary.PSNLibrary.ImportGames() in E:\Devel\Playnite\source\Plugins\PSNLibrary\PSNLibrary.cs:line 201

Diagnostics ID:
1a787c9a-d228-4934-89c2-75fb5fbfa9e5

**Comment by JosefNemec** [comment]
I can't reproduce it myself, but I'll prepare debug build of PSN plugin to help me debug this.

**Comment by adrianluff** [comment]
I did try generating a device code (app password) from the Sony account page. That was sword was not accepted via the web form though.

**Comment by JosefNemec** [comment]
I'm pretty sure that 2FA is not an issue here, since the error is not related to the authentication process. At least for me it works with 2FA just fine.

Please use this [debug build](https://github.com/JosefNemec/Playnite/files/5334957/PSNDebug.zip) of PSN plugin, reproduce the issue again and generate new diag. package. Thank you (the files go into `%localappdata%\playnite\extensions\PSNLibrary\` directory).

**Comment by adrianluff** [comment]
It didn't dawn on me before but I bet the issue is my PSN library is larger than expected. My [download list](https://store.playstation.com/en-us/download/list) shows 6,551 items.

Log message:
> 06-10 12:40:29.432|ERROR|PSNLibrary:Failed to import PSN games.System.NullReferenceException: Object reference not set to an instance of an object.
   at PSNLibrary.PSNLibrary.ParseDownloadList(PSNAccountClient clientApi) in E:\Devel\Playnite\source\Plugins\PSNLibrary\PSNLibrary.cs:line 130
   at PSNLibrary.PSNLibrary.ImportGames() in E:\Devel\Playnite\source\Plugins\PSNLibrary\PSNLibrary.cs:line 201


New diag package from original computer with debug extension:
3142be8b-acf1-4fee-80a7-e209756a8fc3

New diag package from another computer, same account, with debug extension:
53c98711-312d-42f9-a74d-44d6244def96

**Comment by JosefNemec** [comment]
Yeah, the size of the library may cause issues. I got similar report from user on Discord and it seems I will have to adjust some timeouts. Thanks for new diags.

**Comment by JosefNemec** [comment]
Are you sure you've overwritten plugin files correctly? I don't see new debug information in logs and trace lines are from old code as well.

**Comment by adrianluff** [comment]
Ah, nope. I added it to %appdata% not %localappdata%. Fixed.

Log had hundreds of lines like the first line here for different content, then:
> 06-10 13:16:38.946|DEBUG|PSNLibrary:psn ParseDownloadList UP2879-PCSE01056_00-PAPERSPLEASE00NA
06-10 13:16:38.946|ERROR|PSNLibrary:Failed to import PSN games.System.NullReferenceException: Object reference not set to an instance of an object.
   at System.StringExtensions.Contains(String str, String value, StringComparison comparisonType) in E:\Devel\Playnite\source\Playnite.Common\Extensions\StringExtensions.cs:line 143
   at PSNLibrary.PSNLibrary.ParseDownloadList(PSNAccountClient clientApi) in E:\Devel\Playnite\source\Plugins\PSNLibrary\PSNLibrary.cs:line 176
   at PSNLibrary.PSNLibrary.ImportGames() in E:\Devel\Playnite\source\Plugins\PSNLibrary\PSNLibrary.cs:line 209


New package:
e6afb6c8-20e4-4fea-b5eb-dace1182aa25

**Comment by JosefNemec** [comment]
[New version](https://github.com/JosefNemec/Playnite/files/5347485/PSNDebug.zip) of PSN plugin. Let me know if it works with this one.

**Comment by JosefNemec** [comment]
Btw, Sony changed something on their side yesterday/today and the Plugin is now completely broken...

**Comment by adrianluff** [comment]
Sony made a big change to trophy levels yesterday. Not sure how that affected the APIs you use. 

https://blog.playstation.com/2020/10/07/upcoming-trophy-levelling-changes-detailed/

**Comment by JosefNemec** [comment]
[New version](https://github.com/JosefNemec/Playnite/files/5348462/PSNDebug.zip) is available, authentication should now work.

You will also need to replace [these files](https://github.com/JosefNemec/Playnite/files/5348469/PlayniteDebug.zip) in Playnite's install directory, because I had to make changes to the SDK. Make backup of the originals, because some things like IGDB integration will not work with these! They are only for testing of this PSN issue.

**Comment by adrianluff** [comment]
Crashes on startup with those files. I made sure to put them in %localappdata% this time!

> 08-10 09:49:27.599|INFO|PlayniteApplication:Shutting down Playnite
08-10 09:49:27.705|DEBUG|PlayniteApplication:Releasing Playnite resources...
08-10 09:49:48.296|ERROR|Exceptions:Failed check crash stack trace.System.NullReferenceException: Object reference not set to an instance of an object.
   at Playnite.Exceptions.GetExceptionInfo(Exception exception, ExtensionFactory extensions) in E:\Devel\Playnite\source\Playnite\Exceptions.cs:line 34
08-10 09:49:48.339|ERROR|PlayniteApplication:Unhandled exception occured.System.TypeLoadException: Could not load type 'Playnite.Common.DataSerializer' from assembly 'Playnite.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at Playnite.PlayniteApplication.Application_Startup(Object sender, StartupEventArgs e)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at Playnite.PlayniteApplication.Run() in E:\Devel\Playnite\source\Playnite\App\PlayniteApplication.cs:line 438
   at Playnite.DesktopApp.ProgramEntry.Main(String[] args) in E:\Devel\Playnite\source\Playnite.DesktopApp\ProgramEntry.cs:line 51
08-10 09:50:50.583|ERROR|Exceptions:Failed check crash stack trace.System.NullReferenceException: Object reference not set to an instance of an object.
   at Playnite.Exceptions.GetExceptionInfo(Exception exception, ExtensionFactory extensions) in E:\Devel\Playnite\source\Playnite\Exceptions.cs:line 34
08-10 09:50:50.609|ERROR|PlayniteApplication:Unhandled exception occured.System.TypeLoadException: Could not load type 'Playnite.Common.DataSerializer' from assembly 'Playnite.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at Playnite.PlayniteApplication.Application_Startup(Object sender, StartupEventArgs e)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at Playnite.PlayniteApplication.Run() in E:\Devel\Playnite\source\Playnite\App\PlayniteApplication.cs:line 438
   at Playnite.DesktopApp.ProgramEntry.Main(String[] args) in E:\Devel\Playnite\source\Playnite.DesktopApp\ProgramEntry.cs:line 51
08-10 09:56:10.871|ERROR|Exceptions:Failed check crash stack trace.System.NullReferenceException: Object reference not set to an instance of an object.
   at Playnite.Exceptions.GetExceptionInfo(Exception exception, ExtensionFactory extensions) in E:\Devel\Playnite\source\Playnite\Exceptions.cs:line 34
08-10 09:56:10.895|ERROR|PlayniteApplication:Unhandled exception occured.System.TypeLoadException: Could not load type 'Playnite.Common.DataSerializer' from assembly 'Playnite.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at Playnite.PlayniteApplication.Application_Startup(Object sender, StartupEventArgs e)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at Playnite.PlayniteApplication.Run() in E:\Devel\Playnite\source\Playnite\App\PlayniteApplication.cs:line 438
   at Playnite.DesktopApp.ProgramEntry.Main(String[] args) in E:\Devel\Playnite\source\Playnite.DesktopApp\ProgramEntry.cs:line 51
08-10 10:06:15.862|ERROR|Exceptions:Failed check crash stack trace.System.NullReferenceException: Object reference not set to an instance of an object.
   at Playnite.Exceptions.GetExceptionInfo(Exception exception, ExtensionFactory extensions) in E:\Devel\Playnite\source\Playnite\Exceptions.cs:line 34
08-10 10:06:15.887|ERROR|PlayniteApplication:Unhandled exception occured.System.TypeLoadException: Could not load type 'Playnite.Common.DataSerializer' from assembly 'Playnite.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at Playnite.PlayniteApplication.Application_Startup(Object sender, StartupEventArgs e)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at Playnite.PlayniteApplication.Run() in E:\Devel\Playnite\source\Playnite\App\PlayniteApplication.cs:line 438
   at Playnite.DesktopApp.ProgramEntry.Main(String[] args) in E:\Devel\Playnite\source\Playnite.DesktopApp\ProgramEntry.cs:line 51

**Comment by JosefNemec** [comment]
Sorry, I forgot to include one file: [Updated files](https://github.com/JosefNemec/Playnite/files/5348895/PlayniteDebug.zip)

**Comment by adrianluff** [comment]
Still crashing...

> 08-10 10:24:47.803|INFO|PlayniteApplication:Application started from 'C:\Users\adria\AppData\Local\Playnite', with '' arguments.
08-10 10:24:47.834|ERROR|Exceptions:Failed check crash stack trace.System.NullReferenceException: Object reference not set to an instance of an object.
   at Playnite.Exceptions.GetExceptionInfo(Exception exception, ExtensionFactory extensions) in E:\Devel\Playnite\source\Playnite\Exceptions.cs:line 34
08-10 10:24:47.834|ERROR|PlayniteApplication:Unhandled exception occured.System.TypeLoadException: Method 'CreateWindow' in type 'Playnite.DesktopApp.DesktopDialogs' from assembly 'Playnite.DesktopApp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at Playnite.DesktopApp.DesktopApplication.Startup()
   at Playnite.PlayniteApplication.Application_Startup(Object sender, StartupEventArgs e) in E:\Devel\Playnite\source\Playnite\App\PlayniteApplication.cs:line 343
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at Playnite.PlayniteApplication.Run() in E:\Devel\Playnite\source\Playnite\App\PlayniteApplication.cs:line 438
   at Playnite.DesktopApp.ProgramEntry.Main(String[] args) in E:\Devel\Playnite\source\Playnite.DesktopApp\ProgramEntry.cs:line 51
08-10 10:24:59.955|INFO|PlayniteApplication:Application started from 'C:\Users\adria\AppData\Local\Playnite', with '--hidesplashscreen' arguments.
08-10 10:24:59.983|ERROR|Exceptions:Failed check crash stack trace.System.NullReferenceException: Object reference not set to an instance of an object.
   at Playnite.Exceptions.GetExceptionInfo(Exception exception, ExtensionFactory extensions) in E:\Devel\Playnite\source\Playnite\Exceptions.cs:line 34
08-10 10:24:59.983|ERROR|PlayniteApplication:Unhandled exception occured.System.TypeLoadException: Method 'CreateWindow' in type 'Playnite.DesktopApp.DesktopDialogs' from assembly 'Playnite.DesktopApp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at Playnite.DesktopApp.DesktopApplication.Startup()
   at Playnite.PlayniteApplication.Application_Startup(Object sender, StartupEventArgs e) in E:\Devel\Playnite\source\Playnite\App\PlayniteApplication.cs:line 343
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at Playnite.PlayniteApplication.Run() in E:\Devel\Playnite\source\Playnite\App\PlayniteApplication.cs:line 438
   at Playnite.DesktopApp.ProgramEntry.Main(String[] args) in E:\Devel\Playnite\source\Playnite.DesktopApp\ProgramEntry.cs:line 51
08-10 10:25:35.756|INFO|PlayniteApplication:Application started from 'C:\Users\adria\AppData\Local\Playnite', with '--hidesplashscreen' arguments.
08-10 10:25:35.786|ERROR|Exceptions:Failed check crash stack trace.System.NullReferenceException: Object reference not set to an instance of an object.
   at Playnite.Exceptions.GetExceptionInfo(Exception exception, ExtensionFactory extensions) in E:\Devel\Playnite\source\Playnite\Exceptions.cs:line 34
08-10 10:25:35.792|ERROR|PlayniteApplication:Unhandled exception occured.System.TypeLoadException: Method 'CreateWindow' in type 'Playnite.DesktopApp.DesktopDialogs' from assembly 'Playnite.DesktopApp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at Playnite.DesktopApp.DesktopApplication.Startup()
   at Playnite.PlayniteApplication.Application_Startup(Object sender, StartupEventArgs e) in E:\Devel\Playnite\source\Playnite\App\PlayniteApplication.cs:line 343
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at Playnite.PlayniteApplication.Run() in E:\Devel\Playnite\source\Playnite\App\PlayniteApplication.cs:line 438
   at Playnite.DesktopApp.ProgramEntry.Main(String[] args) in E:\Devel\Playnite\source\Playnite.DesktopApp\ProgramEntry.cs:line 51
08-10 10:25:50.458|INFO|PlayniteApplication:Application started from 'C:\Users\adria\AppData\Local\Playnite', with '--hidesplashscreen' arguments.
08-10 10:25:50.482|ERROR|Exceptions:Failed check crash stack trace.System.NullReferenceException: Object reference not set to an instance of an object.
   at Playnite.Exceptions.GetExceptionInfo(Exception exception, ExtensionFactory extensions) in E:\Devel\Playnite\source\Playnite\Exceptions.cs:line 34
08-10 10:25:50.482|ERROR|PlayniteApplication:Unhandled exception occured.System.TypeLoadException: Method 'CreateWindow' in type 'Playnite.DesktopApp.DesktopDialogs' from assembly 'Playnite.DesktopApp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at Playnite.DesktopApp.DesktopApplication.Startup()
   at Playnite.PlayniteApplication.Application_Startup(Object sender, StartupEventArgs e) in E:\Devel\Playnite\source\Playnite\App\PlayniteApplication.cs:line 343
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at Playnite.PlayniteApplication.Run() in E:\Devel\Playnite\source\Playnite\App\PlayniteApplication.cs:line 438
   at Playnite.DesktopApp.ProgramEntry.Main(String[] args) in E:\Devel\Playnite\source\Playnite.DesktopApp\ProgramEntry.cs:line 51

**Comment by JosefNemec** [comment]
Hmm, I guess you would have to have build from devel. I've had another person test this and it works for them (they had similar issue as you). I'll release it with 8.1 update. If it still doesn't work then, let me know.

**Comment by adrianluff** [comment]
Will do.

**Comment by adrianluff** [comment]
Confirmed fixed in 8.1
