### ISSUE TITLE
Bulk metadata download runs off the rails

### ISSUE THREAD

**Issue by HunterZ** [JosefNemec/Playnite#374]
Using version 3.3, when I try to download metadata for all of my games (I have some from each supported provider), Playnite _appears_ to process the entire list. However, it seems that it actually hits a snag at some point and then doesn't actually download/add metadata as it processes subsequent list entries. Some of my Origin games even had unrecognizable names until I told Playnite to download metadata just for those. My battle.net games had no metadata until I told it to download just for those. Et cetera.

I also can't seem to get more than game icons for many games - maybe about 20% of my combined collection of just under 1000 games.

**Comment by HunterZ** [comment]
This is probably related to issue #370. If I set the metadata downloader to prefer Official Store for all items (I think Covers are the only thing that prefer IGDB over Official Store by default) and it seems to work better. It seems that the metadata downloader just doesn't deal well when communication with IGDB fails.

**Comment by JosefNemec** [comment]
Can you go to "About" menu, create diagnostics package and attach it here? Thanks

**Comment by HunterZ** [comment]
[pn.zip](https://github.com/JosefNemec/Playnite/files/1594606/pn.zip)

Here you go. I did a full metadata scan with default settings first, in case it helps.

**Comment by Ianuarius** [comment]
Same problems here. 

* I updated all the info for Blade of Darkness, that I bought from GOG, from IGDB, which changed its name to "Severance: Blade of Darkness", no problem there.
* I selected all the GOG games and ran the Metadata Import tool. I wanted to get the right cover pictures for all of them from the database, so I only left that field checked.
* The tool changed all the info for all the games and even "Severance: Blade of Darkness" back to "Blade of Darkness".
* Also, the cover images are not the same as in IGDB. Many of them are some sort of tinier 16:9 banner versions.

**Comment by JosefNemec** [comment]
@Ianuarius the cover images may stay in 16:9 ratio if Playnite fails to find the game on IGDB (the name might be very different for auto detection to work).

Otherwise all other mentioned points are valid bugs.

**Comment by Ianuarius** [comment]
That might be the case. I just know I downloaded the info both individually and with the Metadata Import tool and got different cover images with each method.

**Comment by JosefNemec** [comment]
Can you guys please test it with [this build](http://playnite.cz/download/metadata.exe)? All problems you've mentioned should be fixed. Thank you

**Comment by HunterZ** [comment]
Seems to work a lot better, thanks. I did notice it scraping additional things after the first attempt, but that could be due to timeouts / too-many-attempts situations.

**Comment by Ianuarius** [comment]
Hmm, it seems the problem really was with the naming of things in my end. The problem is that especially GOG loves to add things to the names of their games, such as "Fallout 2 Classic", "Carmageddon: Max Damage", "Divinity 2 Developer's Cut"... none of which can then be found in IGDB. I'm starting to wonder if there should be some sort of blacklist of phrases that are ignored when doing the automatic metadata fetch.

Of course, another problem are games that are just called something else in different places. A good example of this is Severance: Blade of Darkness. The original subtitle in direct translation from Spanish was Blade: The Edge of Darkness. There was however a show with the same title in the United States, so the US publisher changed the subtitle to Blade of Darkness. And GOG just called the game Blade of Darkness... back when it used to be in their store.

I don't mind doing like a hundred games by hand, but I've got almost 1400 titles on my list... and others have a lot more.

**Comment by JosefNemec** [comment]
Thank you guys for testing this.

@HunterZ There might be some issues still, primarily when downloading data from Steam (they have limit of about 200 requests per minute after which I start slowing down downloads). I will add some proxy caching in future to improve this.

@Ianuarius I'm not sure I can do much about it. I already try to modify names to match them as best as possible. For example I try removing "The" words, consolidate use of ":" and "-" characters, swapping numbers for Roman numerals etc. But there's limit of what I can do before I start introducing false matches and start downloading wrong metadata. And when the store provider chooses to change the name completely (like the Blade of Darkness example), then there's no chance of finding the right data.

**Comment by Ianuarius** [comment]
Absolutely, I agree that unnecessary false positives should be avoided. I think it's more about finding a balance where the end user must to do the least amount of manual work. The way I see it, I'm already getting wrong metadata in a way. Sure, pretty much every game has some data downloaded and I don't think I've seen any that didn't point to the right game due to false matches still getting the data from the store page. I'm just thinking about how many of them I have to do manually.

I've already switched the cover image to 89 games and it takes time. How many of them would have been there in IGDB? Probably a few. Educated guess, about 10% of those. So, that's still 80 games that don't even have the dight image in the IGDB.

I don't think that you should start making any drastic changes to the system at this point. But it's worth thinking about the workload of the end user. Granted, not every user cares about cover images anyway.

Thanks.

**Comment by HunterZ** [comment]
The real problem is a lack of an exhaustive database. Is it easy to look up games on IGDB by their alternate names, when such names are defined?

**Comment by JosefNemec** [comment]
@HunterZ To be honest I didn't even know they have alternative names there :) That would probably take care of some missed matches. I will open that as separate issue.

**Comment by JosefNemec** [comment]
Released in 3.4
