### ISSUE TITLE
Unify cover sizes by using blur effect

### ISSUE THREAD

**Issue by JanPokorny** [JosefNemec/Playnite#580]
Game covers aren't usually the same size, which may look visually unpleasing. The same trick used for converting portrait videos to landscape may help:

Before:

![obrazek](https://user-images.githubusercontent.com/4580066/39880002-b26a69f0-547c-11e8-8dce-c7fa3187f879.png)

After applying the cover, stretched (with aspect ratio preserved), centered, cropped and gauss-blurred as a background:

![obrazek](https://user-images.githubusercontent.com/4580066/39879985-aad02f36-547c-11e8-9032-653a94b5527c.png)

I'm not sure if it helps much, visually... But it may be a backup solution if there is no way to download uniform covers.

**Comment by Continous** [comment]
You could also do it with one of my favorite methods, which is to superimpose the scale image over a guassian blurred 2x larger image and vignette. Demonstrations here:

![Example of Album Art Gaussian Blur](https://i.imgur.com/NkKNWQK.png)

**Comment by Mates1500** [comment]
I suppose this is not being worked on? I could try out both methods and see which fares better, although just from looking at those images I feel the superimposition is more elegant/overall consistent.

However, looking at the [comment here](https://github.com/JosefNemec/Playnite/issues/543#issuecomment-419897947) it would mean that a whole lot of transformed images at different aspect ratios would potentially have to be stored (but practically speaking, people are most likely not gonna change themes like socks).

**Comment by JosefNemec** [comment]
No it's not being worked on and by research I did a while ago it would mean noticeable performance hit on views with a lot of images (the default blurring in WPF is not that great). What I currently plan for 5.0 is to add an option to automatically crop/fit the image to unified sizes.

**Comment by DennoCoil** [comment]
@Mates1500 It would have to be a pre-baking feature where it'd have to do it when downloading metadata or as a single\batch action.  (Several Playnite users here said they have a collection of 5k-15k games.)  Doing it in real-time would be very CPU or GPU intense.

**Comment by Mates1500** [comment]
@JosefNemec is the WPF crop operation fast enough for realtime so that it doesn't heavily affect performance?
My original intention was to cache/bake the images with the blur effect and show those instead in case the aspect ratio of the cover is a little off.
[ImageProcessor](https://github.com/JimBobSquarePants/ImageProcessor) is a nice lightweight library capable of producing gaussian blur for example.

In case of caching for crop, we could perhaps let the user choose in settings which method they'd prefer to consolidate the dimensions? Either the blur or crop.

**Comment by JosefNemec** [comment]
I'm not going to change the image it self, only the way it's displayed (WPF's `Image` control has a support for various display "fitting" options). We already use the same functionality for scaling down the image, performance shouldn't be affected.

**Comment by JosefNemec** [comment]
Done in 5.0

**Comment by tylerszabo** [comment]
In case anyone comes looking in this thread for methods I was able to approximate the way Steam is doing blurring for games with banners only

![image](https://user-images.githubusercontent.com/315343/68454507-b2441e00-01ad-11ea-84e3-d0a9bc14937b.png)

```powershell
& magick convert $in_file -verbose -blur 0x15 `( -clone 0 -gravity north -crop 100%x10%+0+18% `) `( -clone -1 -flip `) `( -clone 0 -gravity south -crop 100%x12%+0+17% -flip `) `( -clone -1 -flip `) `( -clone -1 -flip `) `( -clone -1 -flip `) `( -clone -1 -flip -gravity south -crop 100%x50% `) -delete 0 -append -resize 460x690! $in_file -gravity north -geometry +0+100% -composite $out_file
```

What's still missing is there's a slight rounded darken/saturate effect at the bottom and a corner lighten effect in the top right.
